sudo: required

dist: trusty

services:
  - docker

language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

install:
  - ./mvnw --batch-mode install jacoco:report -B -V
  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'

before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi

script:
  - .travis/deploy.sh

notifications:
  email:
    - haystack-notifications@expedia.com
